version: "2"
services:
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html/
            - ./etc/apache2/sites-available:/etc/apache2/sites-available
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: dw3
            MYSQL_USER: dw3
            MYSQL_PASSWORD: dw3
            MYSQL_ROOT_PASSWORD: dw3
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: dw3
            MYSQL_PASSWORD: dw3
            MYSQL_ROOT_PASSWORD: dw3
volumes:
    persistent: